name: Create Neon Branch for Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neoninc/create-branch-action@v1
        with:
          apiKey: ${{ GitHub repo space4salsa/space-ed }}
          projectId: ${{rapid-surf-57518517}}