name: Create Neon Branch for Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: neoninc/create-branch-action@v1
        with:
          apiKey: ${{ secrets.NEON_API_KEY }}
          projectId: ${{ secrets.NEON_PROJECT_ID }}